IF EXISTS (SELECT * FROM sys.views  
                WHERE object_id = OBJECT_ID(N'[dbo].[VW_ARTICULO]') 
                  )
BEGIN
	DROP VIEW VW_ARTICULO
END

GO

CREATE VIEW VW_ARTICULO
AS

	SELECT A.ID_ARTICULO, A.CVE_FABRICANTE, A.PRECIO, A.ID_FAMILIA, F.NOMBRE_FAMILIA, IA.DESCRIPCION, IA.DESCRIPCION_DETALLADA, A.NOMBRE_ARCHIVO_IMG, A.ACTIVO, IA.ID_IDIOMA 
	FROM CARTICULO A 		
		INNER JOIN RIDIOMA_ARTICULO IA ON A.ID_ARTICULO = IA.ID_ARTICULO
		INNER JOIN VW_FAMILIA F ON A.ID_FAMILIA = F.ID_FAMILIA AND F.ID_IDIOMA = IA.ID_IDIOMA
		
		

	
