IF EXISTS (SELECT * FROM sys.views  
                WHERE object_id = OBJECT_ID(N'[dbo].[VW_CONSIGNATARIO]') 
                  )
BEGIN
	DROP VIEW VW_CONSIGNATARIO
END

GO

CREATE VIEW VW_CONSIGNATARIO
AS

	SELECT ID_CONSIGNATARIO, NOMBRE_COMPLETO, C1.ID_COMUNIDAD, C2.DESC_COMUNIDAD, C1.ACTIVO , E.DESC_ACTIVO, E.ID_IDIOMA
	FROM CCONSIGNATARIO C1 INNER JOIN CCOMUNIDAD C2 ON C1.ID_COMUNIDAD = C2.ID_COMUNIDAD
		INNER JOIN VW_ESTATUS_ACTIVO E ON  C1.ACTIVO = E.ACTIVO 
		
		

	
