IF EXISTS (SELECT * FROM sys.views  
                WHERE object_id = OBJECT_ID(N'[dbo].[VW_ESTATUS_CAJA]') 
                  )
BEGIN
	DROP VIEW VW_ESTATUS_CAJA
END

GO

CREATE VIEW VW_ESTATUS_CAJA
AS

	SELECT F.ID_ESTATUS_CAJA, IFA.DESC_ESTATUS_CAJA, IFA.ID_IDIOMA 
	FROM CESTATUS_CAJA F 
		INNER JOIN RIDIOMA_ESTATUS_CAJA IFA ON F.ID_ESTATUS_CAJA = IFA.ID_ESTATUS_CAJA

	
