--FAMILIAS
SELECT * FROM VW_FAMILIA

SP_ADD_FAMILIA	@ID_IDIOMA = 1

SP_GET_IDIOMA_FAMILIA	@ID_FAMILIA =2

SP_DEL_IDIOMA_FAMILIA	@ID_FAMILIA = 2, 	@ID_IDIOMA_LOGIN = 2
SP_ADD_IDIOMA_FAMILIA	@ID_FAMILIA = 2, 	@DESC_FAMILIA = 'FAMILIA 2', 	@ID_IDIOMA = 1, 	@ID_IDIOMA_LOGIN = 2
SP_ADD_IDIOMA_FAMILIA	@ID_FAMILIA = 2, 	@DESC_FAMILIA = 'FAMILY 2', 	@ID_IDIOMA = 2, 	@ID_IDIOMA_LOGIN = 2

SP_UPD_FAMILIA_ARCHIVO_IMG	@ID_FAMILIA = 1, 	@NOMBRE_ARCHIVO_IMG = 'IMG_FAMILY1.JPG', 	@ID_IDIOMA_LOGIN = 2

SP_GET_FAMILIA 1

--ARTICULO
SP_CMB_FAMILIA 1
SP_ADD_ARTICULO	@ID_IDIOMA = 1, @CVE_FABRICANTE = '0987654321', @PRECIO = 2000.00, @ID_FAMILIA = 2
GO
SP_GET_IDIOMA_ARTICULO	@ID_ARTICULO = 2
GO
SP_DEL_IDIOMA_ARTICULO	@ID_ARTICULO = 2, 	@ID_IDIOMA_LOGIN = 2
GO
SP_ADD_IDIOMA_ARTICULO	@ID_ARTICULO = 2, 	@DESCRIPCION = 'ARTICULO 2', @DESCRIPCION_DETALLADA = 'DETALLE 2', @ID_IDIOMA = 1, 	@ID_IDIOMA_LOGIN = 2
GO
SP_ADD_IDIOMA_ARTICULO	@ID_ARTICULO = 2, 	@DESCRIPCION = 'PRODUCT 2', @DESCRIPCION_DETALLADA = 'DETAIL 2', @ID_IDIOMA = 2, 	@ID_IDIOMA_LOGIN = 2

SP_ADD_ARTICULO	@ID_IDIOMA = 1, @CVE_FABRICANTE = '8979', @PRECIO = 100.00, @ID_FAMILIA = 2

SP_ADD_IDIOMA_ARTICULO	
	@ID_ARTICULO = 32, 	
	@DESCRIPCION = 'ART2 EDEL/,mony DETALLE NULL',  
	
	@ID_IDIOMA = 1, 	
	@ID_IDIOMA_LOGIN = 2


GO
SP_UPD_ARTICULO_ARCHIVO_IMG	@ID_ARTICULO = 1, 	@NOMBRE_ARCHIVO_IMG = 'IMG_ARTICULO1.JPG', 	@ID_IDIOMA_LOGIN = 2
GO
SP_GET_ARTICULO @ID_FAMILIA = 1, @ACTIVO = 1, @ID_IDIOMA = 1, @ID_USUARIO = 1
GO

SP_UPD_ARTICULO_INACTIVAR @ID_ARTICULO = 2, @ID_IDIOMA_LOGIN = 1

SP_UPD_ARTICULO  	@ID_ARTICULO = 32, 	@ID_FAMILIA = 1, 	@CVE_FABRICANTE = 'HDI-123', 	@PRECIO = 500, 	@ID_IDIOMA_LOGIN = 2
--UPDATE CARTICULO SET ACTIVO = 1 WHERE ID_ARTICULO = 32

--CONSIGNATARIOS
SP_ADD_CONSIGNATARIO	@ID_IDIOMA = 1, @NOMBRE_COMPLETO = 'ELFO', @ID_COMUNIDAD = 1
GO
SP_UPD_CONSIGNATARIO @ID_CONSIGNATARIO = 1, @NOMBRE_COMPLETO = 'EDENFLO', 	@ID_IDIOMA_LOGIN = 2
GO
SP_GET_CONSIGNATARIO @ID_USUARIO = 1, @ID_IDIOMA_LOGIN = 1
GO
SP_UPD_CONSIGNATARIO_INACTIVAR   @ID_CONSIGNATARIO = 1,		@ID_IDIOMA_LOGIN = 1

---------------------------------------------
/*
--CHECAR LOS SPs QUE NECESITAN MODIFICARSE PARA USAR LA FUNCIÓN DEL CAMBIO DE FECHA:
	CONSULTA DE MOVIMIMIENTOS, ETC
*/

-- APERTUA DE CAJAS
SP_ADD_CAJA_APERTURA  @NUM_CAJA = 1,@EFECTIVO_INICIAL = 3000, @ID_COMUNIDAD =5 , @ID_USUARIO = 13, @ID_IDIOMA = 2
SP_ADD_CAJA_APERTURA  @NUM_CAJA = 2,@EFECTIVO_INICIAL = 1000, @ID_COMUNIDAD =5 , @ID_USUARIO = 14, @ID_IDIOMA = 2

--LISTADO DE CAJAS
SP_GET_CAJA_APERTURA @ID_USUARIO = 14, 	@FECHA = '04/07/2019', @ID_IDIOMA = 1

UPDATE CCONSIGNATARIO SET ACTIVO = 1 


------------------------------------
--SE HACE UN SELECT A LA CAJAS
SELECT * FROM DCAJA_APERTURA
