IF EXISTS (SELECT * FROM sys.objects 
                WHERE object_id = OBJECT_ID(N'[dbo].[SP_ADD_FAMILIA]') 
                  AND type in (N'P', N'PC'))
BEGIN
	DROP PROCEDURE SP_ADD_FAMILIA
END

GO
CREATE PROCEDURE SP_ADD_FAMILIA  
	@ID_IDIOMA SMALLINT
	
AS  
/*  
SP_ADD_FAMILIA  
AGREGA UN REGISTRO EN CRUBRO
*/  
BEGIN  
	SET NOCOUNT OFF  
	
	DECLARE @ID_FAMILIA SMALLINT
	DECLARE @DESC_MENSAJE NVARCHAR(100)	
	DECLARE @CVE_TIPO_MSG  NVARCHAR(1)

	-- VALOR POR DAFULT
	SET @ID_FAMILIA = 0

	INSERT INTO CFAMILIA (NOMBRE_FAMILIA, ACTIVO)
	VALUES ('DESCRIPCION_TEMPORAL', 1)
   
	SET @ID_FAMILIA = @@IDENTITY

	IF @ID_FAMILIA > 0		
		SELECT @DESC_MENSAJE = DESC_MENSAJE, @CVE_TIPO_MSG = CVE_TIPO_MSG 
		FROM VW_MENSAJES
		WHERE ID_IDIOMA = @ID_IDIOMA AND  ID_MENSAJE = 1 
	ELSE
		SELECT @DESC_MENSAJE = DESC_MENSAJE, @CVE_TIPO_MSG = CVE_TIPO_MSG 
		FROM VW_MENSAJES
		WHERE ID_IDIOMA = @ID_IDIOMA AND  ID_MENSAJE = -1

	-- REGRESAMOS EL MENSAJE QUE APLIQUE	
	SELECT @ID_FAMILIA AS ID,  @DESC_MENSAJE AS  DESC_MENSAJE, @CVE_TIPO_MSG AS CVE_TIPO_MSG

END  

GO
