IF EXISTS (SELECT * FROM sys.objects 
                WHERE object_id = OBJECT_ID(N'[dbo].[SP_ADD_IDIOMA_FAMILIA]') 
                  AND type in (N'P', N'PC'))
BEGIN
	DROP PROCEDURE SP_ADD_IDIOMA_FAMILIA
END

GO
CREATE PROCEDURE SP_ADD_IDIOMA_FAMILIA
	@ID_FAMILIA SMALLINT,
	@DESC_FAMILIA NVARCHAR(20),	
	@ID_IDIOMA SMALLINT,
	@ID_IDIOMA_LOGIN TINYINT
	
AS  
/*  
SP_ADD_IDIOMA_FAMILIA  
AGREGA UN REGISTRO EN RIDIOMA_FAMILIA
*/  
BEGIN  
	SET NOCOUNT OFF  
	
	DECLARE @ID INT
	DECLARE @DESC_MENSAJE NVARCHAR(100)	
	DECLARE @CVE_TIPO_MSG  NVARCHAR(1)

	SET @ID = 0
	INSERT INTO RIDIOMA_FAMILIA (ID_IDIOMA, ID_FAMILIA, NOMBRE_FAMILIA) VALUES (@ID_IDIOMA, @ID_FAMILIA, @DESC_FAMILIA)
	SET @ID = @@ROWCOUNT

	IF @ID_IDIOMA = 1 -- SI ES ESPAÑOL, SE ACTUALIZA ESTA DESCRIPCION EN LA TABLA BASE
		UPDATE CFAMILIA SET NOMBRE_FAMILIA = @DESC_FAMILIA WHERE ID_FAMILIA = @ID_FAMILIA
   

	IF @ID > 0
		SELECT @DESC_MENSAJE = DESC_MENSAJE, @CVE_TIPO_MSG = CVE_TIPO_MSG 
		FROM VW_MENSAJES
		WHERE ID_IDIOMA = @ID_IDIOMA_LOGIN AND  ID_MENSAJE = 1 
	ELSE
		SELECT @DESC_MENSAJE = DESC_MENSAJE, @CVE_TIPO_MSG = CVE_TIPO_MSG 
		FROM VW_MENSAJES
		WHERE ID_IDIOMA = @ID_IDIOMA_LOGIN AND  ID_MENSAJE = -1

	-- REGRESAMOS EL MENSAJE QUE APLIQUE
	SELECT @ID AS ID,  @DESC_MENSAJE AS  DESC_MENSAJE, @CVE_TIPO_MSG AS CVE_TIPO_MSG

END  

GO
