IF EXISTS (SELECT * FROM sys.objects 
                WHERE object_id = OBJECT_ID(N'[dbo].[SP_ADD_ARTICULO]') 
                  AND type in (N'P', N'PC'))
BEGIN
	DROP PROCEDURE SP_ADD_ARTICULO
END

GO
CREATE PROCEDURE SP_ADD_ARTICULO  
	@CVE_FABRICANTE NVARCHAR(30),
	@PRECIO MONEY,
	@ID_FAMILIA INT,
	@ID_IDIOMA SMALLINT
	
AS  
/*  
SP_ADD_ARTICULO  
AGREGA UN REGISTRO EN CARTICULO
*/  
BEGIN  
	SET NOCOUNT OFF  
	
	DECLARE @ID_ARTICULO SMALLINT
	DECLARE @DESC_MENSAJE NVARCHAR(100)	
	DECLARE @CVE_TIPO_MSG  NVARCHAR(1)

	-- VALOR POR DAFULT
	SET @ID_ARTICULO = 0

	INSERT INTO CARTICULO (CVE_FABRICANTE, PRECIO, ID_FAMILIA, DESCRIPCION, DESCRIPCION_DETALLADA, ACTIVO)
	VALUES (@CVE_FABRICANTE, @PRECIO, @ID_FAMILIA, 'DESCRIPCION_TEMPORAL', 'DESCRIPCION_TEMPORAL', 1)
   
	SET @ID_ARTICULO = @@IDENTITY

	IF @ID_ARTICULO > 0		
		SELECT @DESC_MENSAJE = DESC_MENSAJE, @CVE_TIPO_MSG = CVE_TIPO_MSG 
		FROM VW_MENSAJES
		WHERE ID_IDIOMA = @ID_IDIOMA AND  ID_MENSAJE = 1 
	ELSE
		SELECT @DESC_MENSAJE = DESC_MENSAJE, @CVE_TIPO_MSG = CVE_TIPO_MSG 
		FROM VW_MENSAJES
		WHERE ID_IDIOMA = @ID_IDIOMA AND  ID_MENSAJE = -1

	-- REGRESAMOS EL MENSAJE QUE APLIQUE	
	SELECT @ID_ARTICULO AS ID,  @DESC_MENSAJE AS  DESC_MENSAJE, @CVE_TIPO_MSG AS CVE_TIPO_MSG

END  

GO
