IF EXISTS (SELECT * FROM sys.objects 
                WHERE object_id = OBJECT_ID(N'[dbo].[SP_ADD_CONSIGNATARIO]') 
                  AND type in (N'P', N'PC'))
BEGIN
	DROP PROCEDURE SP_ADD_CONSIGNATARIO
END

GO
CREATE PROCEDURE SP_ADD_CONSIGNATARIO 
	@NOMBRE_COMPLETO NVARCHAR(100),
	@ID_COMUNIDAD INT,
	@ID_IDIOMA SMALLINT
	
AS  
/*  
SP_ADD_CONSIGNATARIO  
AGREGA UN REGISTRO EN CCONSIGNATARIO
*/  
BEGIN  
	SET NOCOUNT OFF  
	
	DECLARE @ID_CONSIGNATARIO SMALLINT
	DECLARE @DESC_MENSAJE NVARCHAR(100)	
	DECLARE @CVE_TIPO_MSG  NVARCHAR(1)

	-- VALOR POR DAFULT
	SET @ID_CONSIGNATARIO = 0

	INSERT INTO CCONSIGNATARIO (NOMBRE_COMPLETO, ID_COMUNIDAD, ACTIVO)
	VALUES (@NOMBRE_COMPLETO, @ID_COMUNIDAD, 1)
   
	SET @ID_CONSIGNATARIO = @@IDENTITY

	IF @ID_CONSIGNATARIO > 0		
		SELECT @DESC_MENSAJE = DESC_MENSAJE, @CVE_TIPO_MSG = CVE_TIPO_MSG 
		FROM VW_MENSAJES
		WHERE ID_IDIOMA = @ID_IDIOMA AND  ID_MENSAJE = 1 
	ELSE
		SELECT @DESC_MENSAJE = DESC_MENSAJE, @CVE_TIPO_MSG = CVE_TIPO_MSG 
		FROM VW_MENSAJES
		WHERE ID_IDIOMA = @ID_IDIOMA AND  ID_MENSAJE = -1

	-- REGRESAMOS EL MENSAJE QUE APLIQUE	
	SELECT @ID_CONSIGNATARIO AS ID,  @DESC_MENSAJE AS  DESC_MENSAJE, @CVE_TIPO_MSG AS CVE_TIPO_MSG

END  

GO
