
IF EXISTS (SELECT * FROM sys.objects 
                WHERE object_id = OBJECT_ID(N'[dbo].[SP_CMB_FAMILIA]') 
                  AND type in (N'P', N'PC'))
BEGIN
	DROP PROCEDURE SP_CMB_FAMILIA
END

GO
--LISTA EL COMBO DE LAS FAMILIAS EN EL IDIOMA INDICADO
CREATE PROCEDURE SP_CMB_FAMILIA (
	@ID_IDIOMA TINYINT
) 
AS
BEGIN
	SELECT ID AS ID_FAMILIA, DESCRIPCION AS NOMBRE_FAMILIA
	FROM VW_MENSAJE_SELECCIONE WHERE ID_IDIOMA = @ID_IDIOMA
	UNION
	SELECT ID_FAMILIA, NOMBRE_FAMILIA
	FROM VW_FAMILIA
	WHERE ID_IDIOMA = @ID_IDIOMA

END
