
IF EXISTS (SELECT * FROM sys.objects 
                WHERE object_id = OBJECT_ID(N'[dbo].[SP_CMB_ESTATUS_CAJA]') 
                  AND type in (N'P', N'PC'))
BEGIN
	DROP PROCEDURE SP_CMB_ESTATUS_CAJA
END

GO
--LISTA EL COMBO DE LAS FAMILIAS EN EL IDIOMA INDICADO
CREATE PROCEDURE SP_CMB_ESTATUS_CAJA (
	@ID_IDIOMA TINYINT
) 
AS
BEGIN
	SELECT ID AS ID_ESTATUS_CAJA, DESCRIPCION AS DESC_ESTATUS_CAJA
	FROM VW_MENSAJE_SELECCIONE WHERE ID_IDIOMA = @ID_IDIOMA
	UNION
	SELECT ID_ESTATUS_CAJA, DESC_ESTATUS_CAJA
	FROM VW_ESTATUS_CAJA
	WHERE ID_IDIOMA = @ID_IDIOMA

END
