IF EXISTS (SELECT * FROM sys.objects 
                WHERE object_id = OBJECT_ID(N'dbo.SP_DEL_IDIOMA_FAMILIA') 
                  AND type in (N'P', N'PC'))
BEGIN
	DROP PROCEDURE SP_DEL_IDIOMA_FAMILIA
END

GO
CREATE PROCEDURE SP_DEL_IDIOMA_FAMILIA  
	@ID_FAMILIA SMALLINT,		
	@ID_IDIOMA_LOGIN SMALLINT
	
AS  
/*  
SP_DEL_IDIOMA_FAMILIA  
ELIMINA TODOS LOS REGISTROS DE RIDIOMA_FAMILIA PARA LA FAMILIA INDICADO
*/  
BEGIN  
	
	DECLARE @DESC_MENSAJE NVARCHAR(100)	
	DECLARE @CVE_TIPO_MSG  NVARCHAR(1)
	DECLARE @ACTUALIZACION_OK INT	
	

	-- ELIMINAMOS TODOS LOS PERMISOS PARA ESTE PERFIL
	DELETE RIDIOMA_FAMILIA WHERE ID_FAMILIA = @ID_FAMILIA
	
	SELECT @DESC_MENSAJE = DESC_MENSAJE, @CVE_TIPO_MSG = CVE_TIPO_MSG 
		FROM VW_MENSAJES
		WHERE ID_IDIOMA = @ID_IDIOMA_LOGIN AND  ID_MENSAJE = 4
	SET @ACTUALIZACION_OK = 1
		
	-- REGRESAMOS EL MENSAJE QUE APLIQUE
	SELECT CASE WHEN @ACTUALIZACION_OK > 0 THEN 1 ELSE 0 END AS ID, @DESC_MENSAJE AS  DESC_MENSAJE, @CVE_TIPO_MSG AS CVE_TIPO_MSG

END  

GO
