
IF EXISTS (SELECT * FROM sys.objects 
                WHERE object_id = OBJECT_ID(N'[dbo].[SP_GET_IDIOMA_FAMILIA]') 
                  AND type in (N'P', N'PC'))
BEGIN
	DROP PROCEDURE SP_GET_IDIOMA_FAMILIA
END

GO
--REGRESA TODOS LOS IDIOMAS PARA FAMILIA INDICADA
-- SP_GET_IDIOMA_FAMILIA 38
CREATE PROCEDURE SP_GET_IDIOMA_FAMILIA (
	@ID_FAMILIA SMALLINT
)
AS
BEGIN

	SELECT I.ID_IDIOMA, I.DESC_IDIOMA, ISNULL(R.NOMBRE_FAMILIA, '') AS NOMBRE_FAMILIA
	FROM CIDIOMA I 
		LEFT JOIN RIDIOMA_FAMILIA R ON I.ID_IDIOMA = R.ID_IDIOMA AND ID_FAMILIA = @ID_FAMILIA
	
END
