IF EXISTS (SELECT * FROM sys.objects 
                WHERE object_id = OBJECT_ID(N'[dbo].[SP_GET_OBTEN_MODULOS_PERFIL]') 
                  AND type in (N'P', N'PC'))
BEGIN
	DROP PROCEDURE SP_GET_OBTEN_MODULOS_PERFIL
END

GO
CREATE PROCEDURE SP_GET_OBTEN_MODULOS_PERFIL  
 @ID_PERFIL INT,  
 @ID_MODULO_PRINCIPAL INT,
 @ID_IDIOMA TINYINT
AS  
/*  
SP_GET_OBTEN_MODULOS_PERFIL  @ID_PERFIL = 4, @ID_MODULO_PRINCIPAL = 100000, @ID_IDIOMA = 2
SELECT * FROM SUSUARIO
*/  
BEGIN  

	--MÓDULOS PAPÁ
	SELECT MP.ID_MODULO, IM.NOMBRE_MODULO
	FROM SMODULO_PERFIL  MP 
		INNER JOIN SMODULO M ON MP.ID_MODULO = M.ID_MODULO
		INNER JOIN  RIDIOMA_MODULO IM ON M.ID_MODULO = IM.ID_MODULO
	WHERE ID_PERFIL = @ID_PERFIL AND LEFT(MP.ID_MODULO, 1) * 100000 = @ID_MODULO_PRINCIPAL
		AND ID_MODULO_P > 0 AND IM.ID_IDIOMA = @ID_IDIOMA
		AND M.ID_MODULO_P = @ID_MODULO_PRINCIPAL

	-- MÓDULOS HIJOS
	SELECT MP.ID_MODULO, IM.NOMBRE_MODULO, M.ID_MODULO_P
	FROM SMODULO_PERFIL  MP 
		INNER JOIN SMODULO M ON MP.ID_MODULO = M.ID_MODULO
		INNER JOIN  RIDIOMA_MODULO IM ON M.ID_MODULO = IM.ID_MODULO
	WHERE ID_PERFIL = @ID_PERFIL AND LEFT(MP.ID_MODULO, 1) * 100000 = @ID_MODULO_PRINCIPAL
		AND ID_MODULO_P > 0 AND IM.ID_IDIOMA = @ID_IDIOMA
		AND M.ID_MODULO_P <> @ID_MODULO_PRINCIPAL

END  

GO
