IF EXISTS (SELECT * FROM sys.objects 
                WHERE object_id = OBJECT_ID(N'[dbo].[SP_UPD_FAMILIA_INACTIVAR]') 
                  AND type in (N'P', N'PC'))
BEGIN
	DROP PROCEDURE SP_UPD_FAMILIA_INACTIVAR
END

GO
CREATE PROCEDURE SP_UPD_FAMILIA_INACTIVAR  
	@ID_FAMILIA SMALLINT,	
	@ID_IDIOMA_LOGIN TINYINT
	
AS  
/*  
SP_UPD_FAMILIA_INACTIVAR  
ACTUALIZA EL CAMPO ACRTIVO DE UN REGISTRO EN CFAMILIA
*/  
BEGIN  
	SET NOCOUNT OFF  
	DECLARE @REGS INT -- NÚMERO DE REGISTROS AFECTADOS
	DECLARE @DESC_MENSAJE NVARCHAR(100)	
	DECLARE @CVE_TIPO_MSG  NVARCHAR(1)


	UPDATE CFAMILIA SET ACTIVO = 0 WHERE ID_FAMILIA = @ID_FAMILIA
   
	SET @REGS = @@ROWCOUNT 

	IF @REGS > 0

		SELECT @DESC_MENSAJE = DESC_MENSAJE, @CVE_TIPO_MSG = CVE_TIPO_MSG 
		FROM VW_MENSAJES
		WHERE ID_IDIOMA = @ID_IDIOMA_LOGIN AND  ID_MENSAJE = 4
	ELSE
		SELECT @DESC_MENSAJE = DESC_MENSAJE, @CVE_TIPO_MSG = CVE_TIPO_MSG 
		FROM VW_MENSAJES
		WHERE ID_IDIOMA = @ID_IDIOMA_LOGIN AND  ID_MENSAJE = -1 

	-- REGRESAMOS EL MENSAJE QUE APLIQUE
	SELECT @REGS AS ID, @DESC_MENSAJE AS  DESC_MENSAJE, @CVE_TIPO_MSG AS CVE_TIPO_MSG


END  

GO
