IF EXISTS (SELECT * FROM sys.objects 
                WHERE object_id = OBJECT_ID(N'[dbo].[SP_UPD_ARTICULO]') 
                  AND type in (N'P', N'PC'))
BEGIN
	DROP PROCEDURE SP_UPD_ARTICULO
END

GO
CREATE PROCEDURE SP_UPD_ARTICULO  
	@ID_ARTICULO SMALLINT,		
	@ID_FAMILIA INT,
	@CVE_FABRICANTE NVARCHAR(30),
	@PRECIO MONEY,	
	@ID_IDIOMA_LOGIN TINYINT
AS  
/*  
SP_UPD_ARTICULO  
ACTUALIZA EL CAMPO ACTIVO DE UN REGISTRO EN CARTICULO
*/  
BEGIN  
	SET NOCOUNT OFF  
	DECLARE @REGS INT -- NÚMERO DE REGISTROS AFECTADOS
	DECLARE @DESC_MENSAJE NVARCHAR(100)	
	DECLARE @CVE_TIPO_MSG  NVARCHAR(1)


	UPDATE CARTICULO SET ID_FAMILIA = @ID_FAMILIA, CVE_FABRICANTE= @CVE_FABRICANTE, PRECIO = @PRECIO WHERE ID_ARTICULO = @ID_ARTICULO
   
	SET @REGS = @@ROWCOUNT 

	IF @REGS > 0

		SELECT @DESC_MENSAJE = DESC_MENSAJE, @CVE_TIPO_MSG = CVE_TIPO_MSG 
		FROM VW_MENSAJES
		WHERE ID_IDIOMA = @ID_IDIOMA_LOGIN AND  ID_MENSAJE = 2
	ELSE
		SELECT @DESC_MENSAJE = DESC_MENSAJE, @CVE_TIPO_MSG = CVE_TIPO_MSG 
		FROM VW_MENSAJES
		WHERE ID_IDIOMA = @ID_IDIOMA_LOGIN AND  ID_MENSAJE = -1 

	-- REGRESAMOS EL MENSAJE QUE APLIQUE
	SELECT @REGS AS ID, @DESC_MENSAJE AS  DESC_MENSAJE, @CVE_TIPO_MSG AS CVE_TIPO_MSG


END  

GO
